// <auto-generated />
using System;
using AutoUpdateDemo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AutoUpdateDemo.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20210410112635_innitial_table")]
    partial class innitial_table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AutoUpdateDemo.Models.Installer_Info", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("System")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("cur_version")
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("location")
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("ID");

                    b.ToTable("installers");
                });

            modelBuilder.Entity("AutoUpdateDemo.Models.Installer_Update", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("installer_ID")
                        .HasColumnType("int");

                    b.Property<string>("update_location")
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("version")
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ID");

                    b.ToTable("updates");
                });
#pragma warning restore 612, 618
        }
    }
}
